### ISSUE TITLE
STDCM For long distance path timeout

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#10034]
### What happened?

When searching for an STDCM core timeout.

```
...
[14:20:06,377] [INFO]                  [STDCM] node sample for progress 7/10: time=25982s, since departure=15388s, best remaining time=3940s, loc={lat=44.427971, lon=4.709518}, #visited nodes=204058
[14:20:07,900] [INFO]                  [STDCM] node sample for progress 8/10: time=28157s, since departure=17564s, best remaining time=2618s, loc={lat=44.038597, lon=4.892122}, #visited nodes=214180
fr.sncf.osrd.reporting.exceptions.OSRDError: Pathfinding timed out: no path could be found
    at fr.sncf.osrd.stdcm.graph.STDCMPathfinding.findPathImpl(STDCMPathfinding.kt:193)
    at fr.sncf.osrd.stdcm.graph.STDCMPathfinding.findPath(STDCMPathfinding.kt:123)
    at fr.sncf.osrd.stdcm.graph.STDCMPathfindingKt.findPath(STDCMPathfinding.kt:76)
    at fr.sncf.osrd.api.api_v2.stdcm.STDCMEndpointV2.act(STDCMEndpointV2.kt:105)
    at fr.sncf.osrd.cli.WorkerCommand.run$lambda$8$lambda$3(WorkerCommand.kt:249)
    at fr.sncf.osrd.cli.WorkerCommand.run$lambda$8$lambda$5$lambda$4(WorkerCommand.kt:303)
    at io.opentelemetry.javaagent.bootstrap.executors.ContextPropagatingRunnable.run(ContextPropagatingRunnable.java:37)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    at java.base/java.lang.Thread.run(Thread.java:1583)
```

### What did you expect to happen?

We should be able to find a response on time.

### How can we reproduce it (as minimally and precisely as possible)?

With France infrastructure search for a `DPY.13` to `MAS.AR`.

![Image](https://github.com/user-attachments/assets/e4afe186-2ef0-4aa5-a49f-9c55e3463596)

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

9e75ce2

**Comment by eckter** [comment]
I'm lowering the severity, timeouts can still happen on France but it's *a lot* less common in the South-West lines only

**Comment by eckter** [comment]
This now only happens when requesting paths across the whole country, which is out of scope for now.

**Comment by eckter** [comment]
As we open new areas, it's not out of scope anymore 😄 I'm raising the severity back to major (or is it critical?)

---


Here's the current state:

The timeouts can have 3 causes (or a combination of each):

1. There's no worker currently available and they take too long to start
2. The worker struggles with memory limits
3. It's just too slow / the graph is too large


## Worker issues

As core workers now need to load the full timetable, launching a new worker can be very long (a few minutes). If a user sends a request while there's no worker up and ready, it's *very likely* to result in a timeout. And there's been issues around workers being killed for no identified reason. 

Other than preventing the random kills, we've seen that loading a timetable can be extremely fast if it's loaded from a cache file generated by core [(see here for context)](https://github.com/OpenRailAssociation/osrd/blob/dev/core/src/main/java/fr/sncf/osrd/api/TimetableCacheManager.kt#L148). We could save those files in an S3 or redis, it would save up a lot of time (roughly speaking a few minutes down to just the infra loading time). 

## Memory limits

For the STDCM search, we use a lot of caches that may be cleared by the JVM when nearing the memory limit. 

Normally, these caches are cleared occasionally, where the oldest (least relevant) data gets cleared first. But as the non-clearable memory use gets closer to the limit, the caches don't even last any relevant amount of time. We end up re-computing lots of data and the search gets much slower.

It's not trivial to know when this is the case. During the search, we log some memory data every 10 seconds. But getting close to the memory limit isn't an issue in itself, the problems arise when *the memory that can't be cleared* gets close to the limit. AFAIK there's no way to tell it apart.

We can assume that this happens if the memory use is consistently close to the limit, **and** the number of visited nodes increases much slower than before. 

**Note**: these issues are almost guaranteed to happen if a worker handles more than one request at once. 

## Too slow / graph too large

This isn't an ops matter anymore, we should work on optimizations.

We can:

* Improve the heuristic
* Artificially shrink the graph (e.g by lowering the maximum travel time)
* Hunt for bottlenecks and improve them

I've added details to https://github.com/OpenRailAssociation/osrd/issues/7789 for the purely core parts
