### ISSUE TITLE
api: When creating a study, not specifying the dates causes a silent crash

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#3149]
### What happened?

I created a study without specifying the dates. Nothing happened on the front-end (not even an error). In the `osrd-api` logs, this was printed:

```
osrd-api       | Internal Server Error: /projects/1/studies/
osrd-api       | Traceback (most recent call last):
osrd-api       |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
osrd-api       |     response = get_response(request)
osrd-api       |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
osrd-api       |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
osrd-api       |   File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
osrd-api       |     return view_func(*args, **kwargs)
osrd-api       |   File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
osrd-api       |     return self.dispatch(request, *args, **kwargs)
osrd-api       |   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
osrd-api       |     response = self.handle_exception(exc)
osrd-api       |   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
osrd-api       |     self.raise_uncaught_exception(exc)
osrd-api       |   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
osrd-api       |     raise exc
osrd-api       |   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
osrd-api       |     response = handler(request, *args, **kwargs)
osrd-api       |   File "/home/service/osrd_infra/views/study.py", line 122, in create
osrd-api       |     study = Study.objects.create(project_id=project.id, **request.data)
osrd-api       |   File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
osrd-api       |     return getattr(self.get_queryset(), name)(*args, **kwargs)
osrd-api       |   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 671, in create
osrd-api       |     obj.save(force_insert=True, using=self.db)
osrd-api       |   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 812, in save
osrd-api       |     self.save_base(
osrd-api       |   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 863, in save_base
osrd-api       |     updated = self._save_table(
osrd-api       |   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1006, in _save_table
osrd-api       |     results = self._do_insert(
osrd-api       |   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1047, in _do_insert
osrd-api       |     return manager._insert(
osrd-api       |   File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
osrd-api       |     return getattr(self.get_queryset(), name)(*args, **kwargs)
osrd-api       |   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1791, in _insert
osrd-api       |     return query.get_compiler(using=using).execute_sql(returning_fields)
osrd-api       |   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1659, in execute_sql
osrd-api       |     for sql, params in self.as_sql():
osrd-api       |   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1583, in as_sql
osrd-api       |     value_rows = [
osrd-api       |   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1584, in <listcomp>
osrd-api       |     [
osrd-api       |   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1585, in <listcomp>
osrd-api       |     self.prepare_value(field, self.pre_save_val(field, obj))
osrd-api       |   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1523, in prepare_value
osrd-api       |     value = field.get_db_prep_save(value, connection=self.connection)
osrd-api       |   File "/usr/local/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 925, in get_db_prep_save
osrd-api       |     return self.get_db_prep_value(value, connection=connection, prepared=False)
osrd-api       |   File "/usr/local/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1576, in get_db_prep_value
osrd-api       |     value = self.get_prep_value(value)
osrd-api       |   File "/usr/local/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1554, in get_prep_value
osrd-api       |     value = super().get_prep_value(value)
osrd-api       |   File "/usr/local/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1433, in get_prep_value
osrd-api       |     return self.to_python(value)
osrd-api       |   File "/usr/local/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1536, in to_python
osrd-api       |     raise exceptions.ValidationError(
osrd-api       | django.core.exceptions.ValidationError: ['“” value has an invalid format. It must be in YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ] format.']

```

### What did you expect to happen?

The study should have been created. If the dates are actually mandatory, and error should have been displayed. 

### How can we reproduce it (as minimally and precisely as possible)?

Create a study and don't set the dates

### What operating system and browser are you using? (if applicable)

Ubuntu, firefox

### OSRD version

1.0

**Comment by eckter** [comment]
This appears to be fixed, I can't reproduce it anymore
