### ISSUE TITLE
Bug in standalone CLI simulation [BlockBuilder] no signal at non buffer stop

### ISSUE THREAD

**Issue by ed-rhilbert** [OpenRailAssociation/osrd#3962]
### What happened?

When launching a standalone simulation via the CLI with an infra generated with the python (attached) railjson generator, the following error message appeared:
```
[11:01:56,558] [DEBUG]          [BlockBuilder] no signal at non buffer stop
[11:01:56,564] [DEBUG]          [BlockBuilder] no signal at non buffer stop
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
        at java.base/java.util.Objects.checkIndex(Objects.java:359)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at fr.sncf.osrd.standalone_sim.ScheduleMetadataExtractor.run(ScheduleMetadataExtractor.kt:49)
        at fr.sncf.osrd.standalone_sim.StandaloneSim.run(StandaloneSim.java:62)
        at fr.sncf.osrd.cli.StandaloneSimulationCommand.run(StandaloneSimulationCommand.java:131)
        at fr.sncf.osrd.App.main(App.java:44)
```
[run_py.txt](https://github.com/DGEXSolutions/osrd/files/11284641/run_py.txt)

### What did you expect to happen?

As before

### How can we reproduce it (as minimally and precisely as possible)?

1. Rename the attached file with the extension `.py`
2. Install railjson_generator
3. replace the osrd core path (last line)
4. `python3 run.py`

### What operating system, browser and environment are you using?

- Windows WSL

### OSRD version (top right corner `Account` button > `Informations`)

5cfdb304d7e5ab9d8d2815ba645d1447af26fc56

**Comment by ed-rhilbert** [comment]
Solved by  adding `.add_logical_signal("BAL", settings={"Nf": "false"})` to each signal.
