### ISSUE TITLE
STDCM: AssertionError in CoastingGenerator.coastFromEnd

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#4746]
### What happened?

```
[11:43:54,545] [INFO]                [TkSlf4j] [POST http://dev-core-service.osrd-team-dev.svc.cluster.local:8000/stdcm] returned "HTTP/1.1 500 Internal Server Error" in 14981 ms
	at fr.sncf.osrd.api.stdcm.STDCMEndpoint.act(STDCMEndpoint.java:113)
	at fr.sncf.osrd.stdcm.graph.STDCMPathfinding.findPath(STDCMPathfinding.java:71)
	at fr.sncf.osrd.utils.graph.Pathfinding.runPathfinding(Pathfinding.java:197)
	at fr.sncf.osrd.stdcm.graph.STDCMGraph.getAdjacentEdges(STDCMGraph.java:21)
	at fr.sncf.osrd.stdcm.graph.STDCMGraph.getAdjacentEdges(STDCMGraph.java:92)
	at fr.sncf.osrd.stdcm.graph.STDCMEdgeBuilder.makeAllEdges(STDCMEdgeBuilder.java:156)
	at fr.sncf.osrd.stdcm.graph.STDCMEdgeBuilder.makeSingleEdge(STDCMEdgeBuilder.java:207)
	at fr.sncf.osrd.stdcm.graph.AllowanceManager.tryEngineeringAllowance(AllowanceManager.java:44)
	at fr.sncf.osrd.stdcm.graph.STDCMEdgeBuilder.findEdgeSameNextOccupancy(STDCMEdgeBuilder.java:220)
	at fr.sncf.osrd.stdcm.graph.STDCMEdgeBuilder.makeAllEdges(STDCMEdgeBuilder.java:156)
	at fr.sncf.osrd.stdcm.graph.STDCMEdgeBuilder.makeSingleEdge(STDCMEdgeBuilder.java:207)
	at fr.sncf.osrd.stdcm.graph.AllowanceManager.tryEngineeringAllowance(AllowanceManager.java:44)
	at fr.sncf.osrd.stdcm.graph.STDCMEdgeBuilder.findEdgeSameNextOccupancy(STDCMEdgeBuilder.java:220)
	at fr.sncf.osrd.stdcm.graph.STDCMEdgeBuilder.makeAllEdges(STDCMEdgeBuilder.java:156)
	at fr.sncf.osrd.stdcm.graph.STDCMEdgeBuilder.makeSingleEdge(STDCMEdgeBuilder.java:207)
	at fr.sncf.osrd.stdcm.graph.AllowanceManager.tryEngineeringAllowance(AllowanceManager.java:44)
	at fr.sncf.osrd.stdcm.graph.STDCMEdgeBuilder.findEdgeSameNextOccupancy(STDCMEdgeBuilder.java:220)
	at fr.sncf.osrd.stdcm.graph.STDCMEdgeBuilder.makeAllEdges(STDCMEdgeBuilder.java:156)
	at fr.sncf.osrd.stdcm.graph.STDCMEdgeBuilder.makeSingleEdge(STDCMEdgeBuilder.java:207)
	at fr.sncf.osrd.stdcm.graph.AllowanceManager.tryEngineeringAllowance(AllowanceManager.java:36)
	at fr.sncf.osrd.stdcm.graph.STDCMSimulations.findEngineeringAllowance(STDCMSimulations.java:131)
	at fr.sncf.osrd.envelope_sim.allowances.AbstractAllowanceWithRanges.apply(AbstractAllowanceWithRanges.java:123)
	at fr.sncf.osrd.envelope_sim.allowances.AbstractAllowanceWithRanges.computeAllowanceRegion(AbstractAllowanceWithRanges.java:181)
	at fr.sncf.osrd.envelope_sim.allowances.AbstractAllowanceWithRanges.computeAllowanceRange(AbstractAllowanceWithRanges.java:252)
	at fr.sncf.osrd.envelope_sim.allowances.AbstractAllowanceWithRanges.computeAllowanceSection(AbstractAllowanceWithRanges.java:287)
	at fr.sncf.osrd.envelope_sim.allowances.AbstractAllowanceWithRanges.computeIteration(AbstractAllowanceWithRanges.java:331)
	at fr.sncf.osrd.envelope_sim.allowances.MarecoAllowance.computeCore(MarecoAllowance.java:90)
	at fr.sncf.osrd.envelope_sim.allowances.mareco_impl.AcceleratingSlopeCoast.compute(AcceleratingSlopeCoast.java:122)
	at fr.sncf.osrd.envelope_sim.allowances.mareco_impl.CoastingGenerator.coastFromEnd(CoastingGenerator.java:85)
java.lang.AssertionError
```

### What did you expect to happen?

not applicable

### How can we reproduce it (as minimally and precisely as possible)?

The reproducer is pretty massive, and requires access to the dev instance at SNCF.

![sheet](https://github.com/osrd-project/osrd/assets/5047140/2f8eacb7-0c39-4b2b-82c4-4841648039c9)

from:
![start](https://github.com/osrd-project/osrd/assets/5047140/dedd3439-3a10-40a4-9789-4407cc1c4dca)
to:
![end](https://github.com/osrd-project/osrd/assets/5047140/0176f8bd-9d83-4e35-a683-9692777093bb)

### What operating system, browser and environment are you using?

- **Browser**: Firefox v115
- **OS**: Nixos v23.05
- **Env**: SNCF dev

### OSRD version (top right corner `Account` button > `Informations`)

8d3f0bb511720083442862d49a3ab867c587b55e

**Comment by eckter** [comment]
Can't reproduce, I'll let someone reopen this issue if it happens again
