### ISSUE TITLE
Pathfind in TIVs crashes

### ISSUE THREAD

**Issue by pguenezan** [OpenRailAssociation/osrd#53]
```
java.lang.NullPointerException
	at fr.sncf.osrd.utils.graph.BiDijkstra.findPaths(BiDijkstra.java:62)
	at fr.sncf.osrd.api.PathfindingTracksEndpoint.act(PathfindingTracksEndpoint.java:77)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:157)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:228)
	at org.takes.facets.fork.FkChain.route(FkChain.java:72)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:89)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:57)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:69)
	at org.takes.tk.TkWrap.act(TkWrap.java:58)
	at org.takes.tk.TkSlf4j.act(TkSlf4j.java:92)
	at org.takes.http.BkBasic.print(BkBasic.java:127)
	at org.takes.http.BkBasic.accept(BkBasic.java:103)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:49)
	at org.takes.http.BkWrap.accept(BkWrap.java:51)
	at org.takes.http.FtBasic.loop(FtBasic.java:114)
	at org.takes.http.FtBasic.start(FtBasic.java:100)
	at fr.sncf.osrd.cli.ApiServerCommand.run(ApiServerCommand.java:75)
	at fr.sncf.osrd.App.main(App.java:43)
```

**Comment by pguenezan** [comment]
https://wsend.net/06b4a93bbb601d9622b849e6a5bc7010/infra.rs

**Comment by pguenezan** [comment]
curl -X POST -H 'Accept: application/json' -d '{"infra": 8, "waypoints": [[{"track_section": "track_section.38", "direction": "START_TO_STOP", "offset": 0}], [{"track_section": "track_section.71", "direction": "START_TO_STOP", "offset": 0}]]}' 'http://127.0.0.1:8001/pathfinding/tracks/'

**Comment by flomonster** [comment]
It fails cause `track_section.38` and `track_section.71` doesn't exist in `infra.rs`.
I fixed the returned error.

**Comment by pguenezan** [comment]
ah thanks

**Comment by pguenezan** [comment]
with curl -X POST -H 'Accept: application/json' -d '{"infra": 8, "waypoints": [[{"track_section": "track_section.217", "direction": "START_TO_STOP", "offset": 0}], [{"track_section": "track_section.250", "direction": "START_TO_STOP", "offset": 0}]]}' 'http://127.0.0.1:8001/pathfinding/tracks/'

I have:

```
java.io.IOException: There is no fallback available for java.lang.IndexOutOfBoundsException in org.takes.facets.fallback.FbChain
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:119)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:57)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:69)
	at org.takes.tk.TkWrap.act(TkWrap.java:58)
	at org.takes.tk.TkSlf4j.act(TkSlf4j.java:92)
	at org.takes.http.BkBasic.print(BkBasic.java:127)
	at org.takes.http.BkBasic.accept(BkBasic.java:103)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:49)
	at org.takes.http.BkWrap.accept(BkWrap.java:51)
	at org.takes.http.FtBasic.loop(FtBasic.java:114)
	at org.takes.http.FtBasic.start(FtBasic.java:100)
	at fr.sncf.osrd.cli.ApiServerCommand.run(ApiServerCommand.java:75)
	at fr.sncf.osrd.App.main(App.java:43)
Caused by: java.lang.IllegalStateException: [POST http://127.0.0.1:8001/pathfinding/tracks/] failed in 3s: Index -1 out of bounds for length 0
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:237)
	... 13 more
Caused by: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at fr.sncf.osrd.api.PathfindingTracksEndpoint.act(PathfindingTracksEndpoint.java:100)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:157)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:228)
	at org.takes.facets.fork.FkChain.route(FkChain.java:72)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:89)
	... 12 more
```

**Comment by flomonster** [comment]
It fails because the dijkstra couldn't find a path. The given infra seems invalid since there duplicated track_section_links. Can we make sure that a valid path exists?
