### ISSUE TITLE
core: impossible to load infra in stdcm in certain cases

### ISSUE THREAD

**Issue by SarahBellaha** [OpenRailAssociation/osrd#5618]
### What happened?

Loading an infra fails with a `NullPointerException`

Stack trace:
```
java.lang.NullPointerException
	at fr.sncf.osrd.sim_infra_adapter.RawInfraAdapterKt$adaptRawInfra$2.invoke(RawInfraAdapter.kt:148)
	at fr.sncf.osrd.sim_infra_adapter.RawInfraAdapterKt$adaptRawInfra$2.invoke(RawInfraAdapter.kt:138)
	at fr.sncf.osrd.sim_infra.impl.RawInfraBuilderImpl.movableElement-IvdR598(RawInfraBuilder.kt:305)
	at fr.sncf.osrd.sim_infra_adapter.RawInfraAdapterKt.adaptRawInfra(RawInfraAdapter.kt:138)
	at fr.sncf.osrd.cli.ValidateInfra.run(ValidateInfra.java:43)
	at fr.sncf.osrd.App.main(App.java:42)
```

### What did you expect to happen?

The infra can be loaded.

### How can we reproduce it (as minimally and precisely as possible)?

1. Download [this infra](https://sncf.sharepoint.com/sites/OSRD644GrpO365/_layouts/15/download.aspx?UniqueId=f061dc3eeff1410a82989fed7e5e9918&e=kd92D4) (railjson from the unlocked france Infra [id:1]).
2. Try to load it with core : `java -jar build/libs/osrd-all.jar load-infra --path bad_infra.json`.
3. It fails

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local & Dev

### OSRD version (top right corner `Account` button > `Informations`)

c1679bd9

**Comment by Khoyo** [comment]
This detector has an invalid track:

```
{'id': '5d288569-d94e-44ec-9e1d-2e854761825d', 'track': 'az', 'position': 1, 'extensions': {'sncf': {'kp': '128+850'}}, 'applicable_directions': 'START_TO_STOP'}
```

(And there are no tracks 'az')

Which causes a different error (for good reason).

Are you sure you sent the right railjson file?
