### ISSUE TITLE
STDCM assertion error sanity check on envelope part

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#6072]
### What happened?

Running STDCM can fail with an assertion error.

Core stack trace:
```
	at fr.sncf.osrd.envelope.part.EnvelopePart.runSanityChecks(EnvelopePart.java:164)
	at fr.sncf.osrd.envelope.part.EnvelopePart.slice(EnvelopePart.java:625)
	at fr.sncf.osrd.envelope.part.EnvelopePart.sliceEnd(EnvelopePart.java:512)
	at fr.sncf.osrd.envelope.Envelope.slice(Envelope.java:278)
	at fr.sncf.osrd.envelope.Envelope.slice(Envelope.java:257)
	at fr.sncf.osrd.envelope.OverlayEnvelopeBuilder.sliceBase(OverlayEnvelopeBuilder.java:82)
	at fr.sncf.osrd.envelope.OverlayEnvelopeBuilder.build(OverlayEnvelopeBuilder.java:92)
	at fr.sncf.osrd.envelope_sim.pipelines.MaxEffortEnvelope.addAccelerationAndConstantSpeedParts(MaxEffortEnvelope.java:100)
	at fr.sncf.osrd.envelope_sim.pipelines.MaxEffortEnvelope.from(MaxEffortEnvelope.java:135)
	at fr.sncf.osrd.stdcm.graph.STDCMSimulationsKt.simulateBlock-E0Rpq9g(STDCMSimulations.kt:127)
	at fr.sncf.osrd.stdcm.graph.STDCMSimulations.simulateBlock(STDCMSimulations.kt:53)
	at fr.sncf.osrd.stdcm.graph.STDCMEdgeBuilder.getEnvelope(STDCMEdgeBuilder.kt:138)
	at fr.sncf.osrd.stdcm.graph.STDCMEdgeBuilder.makeAllEdges(STDCMEdgeBuilder.kt:111)
	at fr.sncf.osrd.stdcm.graph.STDCMGraph.getAdjacentEdges(STDCMGraph.kt:79)
	at fr.sncf.osrd.stdcm.graph.STDCMGraph.getAdjacentEdges(STDCMGraph.kt:21)
	at fr.sncf.osrd.graph.Pathfinding.runPathfinding(Pathfinding.kt:207)
	at fr.sncf.osrd.stdcm.graph.STDCMPathfindingKt.findPath(STDCMPathfinding.kt:80)
	at fr.sncf.osrd.api.stdcm.STDCMEndpoint.act(STDCMEndpoint.kt:74)
	at org.takes.facets.fork.FkRegex.lambda$new$0(FkRegex.java:153)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:217)
	at org.takes.facets.fork.FkChain.route(FkChain.java:72)
	at org.takes.facets.fork.TkFork.act(TkFork.java:98)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:84)
	at org.takes.facets.fallback.TkFallback.lambda$new$0(TkFallback.java:66)
	at org.takes.tk.TkWrap.act(TkWrap.java:58)
	at org.takes.tk.TkSlf4j.act(TkSlf4j.java:110)
	at org.takes.http.BkBasic.print(BkBasic.java:123)
	at org.takes.http.BkBasic.accept(BkBasic.java:99)
	at org.takes.http.BkSafe.lambda$new$0(BkSafe.java:46)
	at org.takes.http.BkWrap.accept(BkWrap.java:51)
	at org.takes.http.BkParallel.lambda$new$0(BkParallel.java:81)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$W
```

### How can we reproduce it (as minimally and precisely as possible)?

1. Use France infra
2. Create a train from (PLY to VCE) using 27000US
3. Search of a STDCM with the same parameters

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local & Dev

### OSRD version (top right corner `Account` button > `Informations`)

e78edcf

**Comment by axrolld** [comment]
This looks major to me, if not, feel free ton change the label :)
