### ISSUE TITLE
"The infrastructure contains errors" message while no error detected in infra editor

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#6159]
### What happened?

I edited an infrastructure, fixed all the errors :
![image](https://github.com/osrd-project/osrd/assets/86296016/37eb40ed-7400-437e-9399-31b66212ca56)
![image](https://github.com/osrd-project/osrd/assets/86296016/84f7f338-3958-4f28-a4c7-92c7ab3181ef)

But still when trying to use it in a scenario it says that my infrastructure has errors:
![image](https://github.com/osrd-project/osrd/assets/86296016/d38e69b9-cda6-4944-ba92-a55ff9fe27e9)

### What did you expect to happen?

If the infrastructure editor says my infrastructure has no errors i should be able to use it.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to my scenario Alex>Reproduction de bug>Train

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: dev dgexsol

### OSRD version (top right corner `Account` button > `Informations`)

faae221

**Comment by flomonster** [comment]
Core stack trace:

```
fr.sncf.osrd.reporting.exceptions.OSRDError: hard error while loading new infra
	at fr.sncf.osrd.reporting.exceptions.OSRDError.newInfraLoadingError(OSRDError.java:141)
	at fr.sncf.osrd.api.InfraManager.downloadInfra(InfraManager.java:181)
	at fr.sncf.osrd.api.InfraManager.load(InfraManager.java:207)
	at fr.sncf.osrd.api.InfraLoadEndpoint.act(InfraLoadEndpoint.java:37)
	at org.takes.facets.fork.FkRegex.lambda$new$0(FkRegex.java:153)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:217)
	at org.takes.facets.fork.FkChain.route(FkChain.java:72)
	at org.takes.facets.fork.TkFork.act(TkFork.java:98)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:84)
	at org.takes.facets.fallback.TkFallback.lambda$new$0(TkFallback.java:66)
	at org.takes.tk.TkWrap.act(TkWrap.java:58)
	at org.takes.tk.TkSlf4j.act(TkSlf4j.java:110)
	at org.takes.http.BkBasic.print(BkBasic.java:123)
	at org.takes.http.BkBasic.accept(BkBasic.java:99)
	at org.takes.http.BkSafe.lambda$new$0(BkSafe.java:46)
	at org.takes.http.BkWrap.accept(BkWrap.java:51)
	at org.takes.http.BkParallel.lambda$new$0(BkParallel.java:81)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NullPointerException: null
	at fr.sncf.osrd.sim_infra_adapter.RawInfraAdapterKt$adaptRawInfra$2.invoke(RawInfraAdapter.kt:148)
	at fr.sncf.osrd.sim_infra_adapter.RawInfraAdapterKt$adaptRawInfra$2.invoke(RawInfraAdapter.kt:138)
	at fr.sncf.osrd.sim_infra.impl.RawInfraBuilderImpl.movableElement-IvdR598(RawInfraBuilder.kt:305)
	at fr.sncf.osrd.sim_infra_adapter.RawInfraAdapterKt.adaptRawInfra(RawInfraAdapter.kt:138)
	at fr.sncf.osrd.api.InfraManager.downloadInfra(InfraManager.java:158)
fr.sncf.osrd.reporting.exceptions.OSRDError: hard error while loading new infra
	... 18 common frames omitted
	at fr.sncf.osrd.reporting.exceptions.OSRDError.newInfraLoadingError(OSRDError.java:141)
	at fr.sncf.osrd.api.InfraManager.downloadInfra(InfraManager.java:181)
	at fr.sncf.osrd.api.InfraManager.load(InfraManager.java:207)
	at fr.sncf.osrd.api.InfraLoadEndpoint.act(InfraLoadEndpoint.java:37)
	at org.takes.facets.fork.FkRegex.lambda$new$0(FkRegex.java:153)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:217)
	at org.takes.facets.fork.FkChain.route(FkChain.java:72)
	at org.takes.facets.fork.TkFork.act(TkFork.java:98)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:84)
	at org.takes.facets.fallback.TkFallback.lambda$new$0(TkFallback.java:66)
	at org.takes.tk.TkWrap.act(TkWrap.java:58)
	at org.takes.tk.TkSlf4j.act(TkSlf4j.java:110)
	at org.takes.http.BkBasic.print(BkBasic.java:123)
	at org.takes.http.BkBasic.accept(BkBasic.java:99)
	at org.takes.http.BkSafe.lambda$new$0(BkSafe.java:46)
	at org.takes.http.BkWrap.accept(BkWrap.java:51)
	at org.takes.http.BkParallel.lambda$new$0(BkParallel.java:81)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NullPointerException
	at fr.sncf.osrd.sim_infra_adapter.RawInfraAdapterKt$adaptRawInfra$2.invoke(RawInfraAdapter.kt:148)
	at fr.sncf.osrd.sim_infra_adapter.RawInfraAdapterKt$adaptRawInfra$2.invoke(RawInfraAdapter.kt:138)
	at fr.sncf.osrd.sim_infra.impl.RawInfraBuilderImpl.movableElement-IvdR598(RawInfraBuilder.kt:305)
	at fr.sncf.osrd.sim_infra_adapter.RawInfraAdapterKt.adaptRawInfra(RawInfraAdapter.kt:138)
	at fr.sncf.osrd.api.InfraManager.downloadInfra(InfraManager.java:158)
```

**Comment by flomonster** [comment]
This is due to weird nodes. We link an endpoint to itself.
We should:
- [ ] https://github.com/osrd-project/osrd/issues/6078
- [ ] Editoast should return an error when nodes overlap itself

**Comment by axrolld** [comment]
Got the same bug on staging internal, project `X`, study `Y`, scenario `New Infra`.

The infrastructure has no errors in the editor but the scenario is locked.

**Comment by axrolld** [comment]
This bug might be linked to this one https://github.com/osrd-project/osrd/issues/6392
It's another infractructure bug that the editor does not detect.

**Comment by axrolld** [comment]
Can't reproduce by now, i'm closing this.
