### ISSUE TITLE
core crashloop backoff when opening a timetable with 2000 trains not in cache

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#8771]
### What happened?

See the logs:

<details>

```
Sep 05 14:41:14.918
Sep 05 14:41:14.918
	
at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:469)
	
Sep 05 14:41:14.918
Sep 05 14:41:14.918
	
at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:281)
	
Sep 05 14:41:14.918
Sep 05 14:41:14.918
	
com.rabbitmq.client.AlreadyClosedException: connection is already closed due to connection error; cause: java.io.EOFException
	
Sep 05 14:41:14.918
Sep 05 14:41:14.918
	
[12:41:14,128] [1;31m[ERROR][0;39m [ForgivingExceptionHandler] Consumer datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer@5a63f30 (amq.ctag-qocnm821037KQdbUaxrVmA) method handleDelivery for channel AMQChannel(amqp://osrd@10.170.113.148:5672/,2) threw an exception for channel AMQChannel(amqp://osrd@10.170.113.148:5672/,2)
	
Sep 05 14:41:14.918
Sep 05 14:41:14.918
	
at java.base/java.lang.Thread.run(Thread.java:1583)
	
Sep 05 14:41:14.918
Sep 05 14:41:14.918
	
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	
Sep 05 14:41:14.918
Sep 05 14:41:14.918
	
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	
Sep 05 14:41:14.918
Sep 05 14:41:14.918
	
at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:111)
	
Sep 05 14:41:14.918
Sep 05 14:41:14.918
	
at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
	
Sep 05 14:41:14.918
Sep 05 14:41:14.918
	
at datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer.handleDelivery(TracedDelegatingConsumer.java:79)
	
Sep 05 14:41:14.918
Sep 05 14:41:14.918
	
at com.rabbitmq.client.impl.recovery.AutorecoveringChannel$4.handleDelivery(AutorecoveringChannel.java:642)
	
Sep 05 14:41:14.918
Sep 05 14:41:14.918
	
at fr.sncf.osrd.cli.WorkerCommand.run$lambda$2(WorkerCommand.kt:122)
	
Sep 05 14:41:14.918
Sep 05 14:41:14.918
	
at fr.sncf.osrd.cli.WorkerCommand.reportActivity(WorkerCommand.kt:231)
	
Sep 05 14:41:14.918
Sep 05 14:41:14.918
	
at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.basicPublish(AutorecoveringChannel.java:207)
	
Sep 05 14:41:14.918
Sep 05 14:41:14.918
	
at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:693)
	
Sep 05 14:41:14.918
Sep 05 14:41:14.918
	
at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:703)
	
Sep 05 14:41:14.918
Sep 05 14:41:14.918
	
at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:731)
	
Sep 05 14:41:14.918
Sep 05 14:41:14.918
	
at com.rabbitmq.client.observation.NoOpObservationCollector.publish(NoOpObservationCollector.java:33)
	
Sep 05 14:41:14.918
Sep 05 14:41:14.918
	
at com.rabbitmq.client.impl.ChannelN.lambda$basicPublish$1(ChannelN.java:729)
	
Sep 05 14:41:14.918
Sep 05 14:41:14.918
	
at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:469)
	
Sep 05 14:41:14.918
Sep 05 14:41:14.918
	
at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:281)
	
Sep 05 14:41:14.918
Sep 05 14:41:14.918
	
com.rabbitmq.client.AlreadyClosedException: connection is already closed due to connection error; cause: java.io.EOFException
	
Sep 05 14:41:14.918
Sep 05 14:41:14.918
	
[12:41:14,121] [1;31m[ERROR][0;39m [ForgivingExceptionHandler] Consumer datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer@5a63f30 (amq.ctag-qocnm821037KQdbUaxrVmA) method handleDelivery for channel AMQChannel(amqp://osrd@10.170.113.148:5672/,2) threw an exception for channel AMQChannel(amqp://osrd@10.170.113.148:5672/,2)
	
Sep 05 14:41:14.918
Sep 05 14:41:14.918
	
at java.base/java.lang.Thread.run(Thread.java:1583)
	
Sep 05 14:41:14.918
Sep 05 14:41:14.918
	
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	
Sep 05 14:41:14.918
Sep 05 14:41:14.918
	
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	
Sep 05 14:41:14.918
Sep 05 14:41:14.918
	
at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:111)
	
Sep 05 14:41:14.918
Sep 05 14:41:14.918
	
at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
	
Sep 05 14:41:14.918
Sep 05 14:41:14.918
	
at datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer.handleDelivery(TracedDelegatingConsumer.java:79)
	
Sep 05 14:41:14.918
Sep 05 14:41:14.918
	
at com.rabbitmq.client.impl.recovery.AutorecoveringChannel$4.handleDelivery(AutorecoveringChannel.java:642)
	
Sep 05 14:41:14.918
Sep 05 14:41:14.918
	
at fr.sncf.osrd.cli.WorkerCommand.run$lambda$2(WorkerCommand.kt:122)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at fr.sncf.osrd.cli.WorkerCommand.reportActivity(WorkerCommand.kt:231)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.basicPublish(AutorecoveringChannel.java:207)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:693)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:703)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:731)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at com.rabbitmq.client.observation.NoOpObservationCollector.publish(NoOpObservationCollector.java:33)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at com.rabbitmq.client.impl.ChannelN.lambda$basicPublish$1(ChannelN.java:729)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:469)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:281)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
com.rabbitmq.client.AlreadyClosedException: connection is already closed due to connection error; cause: java.io.EOFException
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
[12:41:14,120] [1;31m[ERROR][0;39m [ForgivingExceptionHandler] Consumer datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer@5a63f30 (amq.ctag-qocnm821037KQdbUaxrVmA) method handleDelivery for channel AMQChannel(amqp://osrd@10.170.113.148:5672/,2) threw an exception for channel AMQChannel(amqp://osrd@10.170.113.148:5672/,2)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at java.base/java.lang.Thread.run(Thread.java:1583)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:111)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer.handleDelivery(TracedDelegatingConsumer.java:79)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at com.rabbitmq.client.impl.recovery.AutorecoveringChannel$4.handleDelivery(AutorecoveringChannel.java:642)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at fr.sncf.osrd.cli.WorkerCommand.run$lambda$2(WorkerCommand.kt:122)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at fr.sncf.osrd.cli.WorkerCommand.reportActivity(WorkerCommand.kt:231)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.basicPublish(AutorecoveringChannel.java:207)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:693)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:703)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:731)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at com.rabbitmq.client.observation.NoOpObservationCollector.publish(NoOpObservationCollector.java:33)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at com.rabbitmq.client.impl.ChannelN.lambda$basicPublish$1(ChannelN.java:729)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:469)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:281)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
com.rabbitmq.client.AlreadyClosedException: connection is already closed due to connection error; cause: java.io.EOFException
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
[12:41:14,119] [1;31m[ERROR][0;39m [ForgivingExceptionHandler] Consumer datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer@5a63f30 (amq.ctag-qocnm821037KQdbUaxrVmA) method handleDelivery for channel AMQChannel(amqp://osrd@10.170.113.148:5672/,2) threw an exception for channel AMQChannel(amqp://osrd@10.170.113.148:5672/,2)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at java.base/java.lang.Thread.run(Thread.java:1583)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:111)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer.handleDelivery(TracedDelegatingConsumer.java:79)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at com.rabbitmq.client.impl.recovery.AutorecoveringChannel$4.handleDelivery(AutorecoveringChannel.java:642)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at fr.sncf.osrd.cli.WorkerCommand.run$lambda$2(WorkerCommand.kt:122)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at fr.sncf.osrd.cli.WorkerCommand.reportActivity(WorkerCommand.kt:231)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.basicPublish(AutorecoveringChannel.java:207)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:693)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:703)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:731)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at com.rabbitmq.client.observation.NoOpObservationCollector.publish(NoOpObservationCollector.java:33)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at com.rabbitmq.client.impl.ChannelN.lambda$basicPublish$1(ChannelN.java:729)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:469)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:281)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
com.rabbitmq.client.AlreadyClosedException: connection is already closed due to connection error; cause: java.io.EOFException
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
[12:41:14,119] [1;31m[ERROR][0;39m [ForgivingExceptionHandler] Consumer datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer@5a63f30 (amq.ctag-qocnm821037KQdbUaxrVmA) method handleDelivery for channel AMQChannel(amqp://osrd@10.170.113.148:5672/,2) threw an exception for channel AMQChannel(amqp://osrd@10.170.113.148:5672/,2)
	
Sep 05 14:41:14.917
Sep 05 14:41:14.917
	
at java.base/java.lang.Thread.run(Thread.java:1583)
```

</details>

### What did you expect to happen?

The current solution is to empty the queue right now...

### How can we reproduce it (as minimally and precisely as possible)?

1. open a huge timetable on rec-osrd.reseau.sncf.fr

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

c2b8718

**Comment by flomonster** [comment]
Can't reproduce
