### ISSUE TITLE
Error in browser console when "precise time" is selected on Origin or Destination form in STDCM interface

### ISSUE THREAD

**Issue by kmer2016** [OpenRailAssociation/osrd#8821]
### What happened?

When the Select component used to set time constraints on Origin or Destination is set to 'Precise Time', an error is displayed in the browser console :
```
chunk-QYYA6GZJ.js?v=19e41fd2:521 Warning: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.
    at input
    at div
    at div
    at div
    at div
    at div
    at F (http://localhost:4000/node_modules/.vite/deps/chunk-YPEUWSDC.js?v=19e41fd2:123:16)
    at http://localhost:4000/node_modules/.vite/deps/chunk-YPEUWSDC.js?v=19e41fd2:137:13
    at div
    at div
    at ge (http://localhost:4000/node_modules/.vite/deps/chunk-YPEUWSDC.js?v=19e41fd2:377:177)
    at div
    at div
    at div
    at StdcmOpSchedule (http://localhost:4000/src/applications/stdcmV2/components/StdcmOpSchedule.tsx:24:28)
    at div
    at div
    at div
    at StdcmCard (http://localhost:4000/src/applications/stdcmV2/components/StdcmCard.tsx:11:22)
    at StdcmOrigin (http://localhost:4000/src/applications/stdcmV2/components/StdcmOrigin.tsx:22:24)
    at div
    at div
    at div
    at StdcmConfig (http://localhost:4000/src/applications/stdcmV2/components/StdcmConfig.tsx:30:24)
    at div
    at div
    at StdcmViewV2 (http://localhost:4000/src/applications/stdcmV2/views/StdcmViewV2.tsx:24:32)
    at RenderedRoute (http://localhost:4000/node_modules/.vite/deps/react-router-dom.js?v=07136236:3560:5)
    at Routes (http://localhost:4000/node_modules/.vite/deps/react-router-dom.js?v=07136236:3995:5)
    at HomeStdcm (http://localhost:4000/src/applications/stdcm/Home.tsx:21:30)
    at RenderedRoute (http://localhost:4000/node_modules/.vite/deps/react-router-dom.js?v=07136236:3560:5)
    at Outlet (http://localhost:4000/node_modules/.vite/deps/react-router-dom.js?v=07136236:3931:26)
    at ModalProvider (http://localhost:4000/src/common/BootstrapSNCF/ModalSNCF/ModalProvider.tsx:75:37)
    at OsrdContextLayout (http://localhost:4000/src/common/osrdContext.tsx:104:37)
    at RenderedRoute (http://localhost:4000/node_modules/.vite/deps/react-router-dom.js?v=07136236:3560:5)
    at RenderErrorBoundary (http://localhost:4000/node_modules/.vite/deps/react-router-dom.js?v=07136236:3520:5)
    at DataRoutes (http://localhost:4000/node_modules/.vite/deps/react-router-dom.js?v=07136236:4670:5)
    at Router (http://localhost:4000/node_modules/.vite/deps/react-router-dom.js?v=07136236:3938:15)
    at RouterProvider (http://localhost:4000/node_modules/.vite/deps/react-router-dom.js?v=07136236:4487:5)
    at Suspense
    at App (http://localhost:4000/src/main/app.jsx:194:22)
    at PersistGate2 (http://localhost:4000/node_modules/.vite/deps/redux-persist_integration_react.js?v=f9d3f2f7:90:5)
    at Provider (http://localhost:4000/node_modules/.vite/deps/chunk-6HQ3C4LF.js?v=19e41fd2:1095:3)
    at Container
```

### What did you expect to happen?

No error message

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to STDCM interface.
2. On Origin/Destination card, select "precise time" on time constraints selector

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Google Chrome, Other

### OSRD version (top right corner `Account` button > `Informations`)

dev

**Comment by clarani** [comment]
Can't reproduce, it must have been solved lately :white_check_mark:
